## Configuration file

name: Alicht CSS
root_url: /

author: William Dorffer
description: Alicht CSS framework, originally made for archost.eu
title: Alicht CSS

markdown: kramdown

gems:
  - jekyll-redirect-from

menu:
- text: Alicht on <span class="octicon octicon-mark-github"></span>
  url: https://github.com/archost/alicht
